/** Mirrors backend `PermissionCodes` for UI checks. */
export const PermissionCodes = {
  UserManage: 'USER_MANAGE',
  RoleManage: 'ROLE_MANAGE',
  EmployeeView: 'EMPLOYEE_VIEW',
  EmployeeEdit: 'EMPLOYEE_EDIT',
  CompetencyView: 'COMPETENCY_VIEW',
  CompetencyEdit: 'COMPETENCY_EDIT',
  PerformanceView: 'PERFORMANCE_VIEW',
  PerformanceManage: 'PERFORMANCE_MANAGE',
  PotentialView: 'POTENTIAL_VIEW',
  PotentialManage: 'POTENTIAL_MANAGE',
  ScoringView: 'SCORING_VIEW',
  ScoringManage: 'SCORING_MANAGE',
  ClassificationView: 'CLASSIFICATION_VIEW',
  ClassificationManage: 'CLASSIFICATION_MANAGE',
  SuccessionView: 'SUCCESSION_VIEW',
  SuccessionManage: 'SUCCESSION_MANAGE',
  DevelopmentView: 'DEVELOPMENT_VIEW',
  DevelopmentManage: 'DEVELOPMENT_MANAGE',
  MarketplaceView: 'MARKETPLACE_VIEW',
  MarketplaceManage: 'MARKETPLACE_MANAGE',
  MarketplaceApply: 'MARKETPLACE_APPLY',
  AnalyticsView: 'ANALYTICS_VIEW',
  ApprovalRequestCreate: 'APPROVAL_REQUEST_CREATE',
  ApprovalRequestView: 'APPROVAL_REQUEST_VIEW',
  ApprovalRequestAssign: 'APPROVAL_REQUEST_ASSIGN',
  ApprovalRequestReview: 'APPROVAL_REQUEST_REVIEW',
  ApprovalRequestApprove: 'APPROVAL_REQUEST_APPROVE',
  ApprovalRequestReject: 'APPROVAL_REQUEST_REJECT',
  NotificationView: 'NOTIFICATION_VIEW',
  NotificationManage: 'NOTIFICATION_MANAGE',
  IntelligenceView: 'INTELLIGENCE_VIEW',
  IntelligenceGenerate: 'INTELLIGENCE_GENERATE',
  IntelligenceManage: 'INTELLIGENCE_MANAGE',
} as const;

export type PermissionCode = (typeof PermissionCodes)[keyof typeof PermissionCodes];
